workflows:
  primary:
    name: Build and Test
    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"  # Optional: Disable Gradle daemon
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug  # Replace with assembleRelease for release build
      - name: Archive artifacts
        script: |
          mkdir -p $CM_BUILD_DIR/artifacts
          mv $CM_BUILD_DIR/app/build/outputs/apk/debug/*.apk $CM_BUILD_DIR/artifacts/
    artifacts:
      - $CM_BUILD_DIR/artifacts/*.apk  # Adjust the path based on your build configuration
